# Site settings
title: Bioinformatcis
SEOTitle: Yingshan | 李应山
header-img: img/bio.ico
email: lys_life@163.com
description: "Every failure is leading towards success."
keyword: "Python, Linux, Perl, R, Bioinformatics, Machine Learning, Precision medicine"
url: "http://yingshanli.github.io"
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/yingshanli/yingshanli.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "站得高才能望得远！"
sidebar-avatar: /img/yingshan.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     
zhihu_username:     li-ying-shan-3
github_username:    yingshanli
#facebook_username:  
jianshu_username:   ddb2e2b967be
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: yingshanl

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 01ba771380a7a20c4e38   #生成的clientID
  clientSecret: 7f4ce1923885f53bd8fd407ca314a0c3710478c4  #同上
  repo: yingshanli.github.io    #仓库名称
  owner: yingshanli    #github用户名
  admin: yingshanli
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: 

# Google Analytics
ga_track_id: 'UA-112759826-1'            # Format: UA-xxxxxx-xx
#ga_domain: shan-shan.family               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "zhihu",
        href: "https://www.zhihu.com/people/li-ying-shan-3/activities"
    },{
        title: "简书·李应山",
        href: "https://www.jianshu.com/users/ddb2e2b967be/timeline"
    },{
        #title: "Apple",
        #href: "https://apple.com"
    },{
        #title: "Apple Developer",
        #href: "https://developer.apple.com/"
    }
]
